### ISSUE TITLE
Please provide a valid cache path.

### ISSUE THREAD

**Issue by webafra** [jackbrycesmith/laravel-caprover-template#17]
hi .

i have a problem to deploy.
i get this error after deploy laravel:

**laravel version: 7.30.4**

Please provide a valid cache path.

![delpoy-laravel](https://user-images.githubusercontent.com/8689072/122856791-ab3f3480-d32c-11eb-876e-99bf88ff0354.png)

**Comment by jackbrycesmith** [comment]
Hey it looks like you need to make sure directories under `storage/framework` are committed before you deploy.

- https://github.com/laravel/laravel/tree/8.x/storage/framework

This should be present by default when you install laravel, but assume its gone missing for you somehow!

- https://stackoverflow.com/questions/38483837/please-provide-a-valid-cache-path-error-in-laravel

**Comment by webafra** [comment]
thanks for your answer but there is this directory:

i deploy project from gitlab repository

<img width="990" alt="Screen Shot 2021-06-23 at 4 18 18 AM" src="https://user-images.githubusercontent.com/8689072/123014007-8d300d80-d3da-11eb-8ec8-296987f23bbb.png">

**Comment by jackbrycesmith** [comment]
`views` seems to be missing from that screenshot? Pretty sure it needs to be there.

https://github.com/laravel/laravel/tree/8.x/storage/framework/views

**Comment by webafra** [comment]
thanks .
this resolved.
