### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by germanatunify** [jackbrycesmith/laravel-caprover-template#2]
Hello, I found some issues with the entrypoint.sh, I got the error:

`standard_init_linux.go:211: exec user process caused "no such file or directory"`

So I edited the  Dockerfile last line to this, it's weird because the entrypoint.sh first line is calling #!/bin/sh. But, still, here it is.

`ENTRYPOINT ["/bin/bash","/entrypoint.sh"]`

**Comment by jackbrycesmith** [comment]
Yeah that does seem weird, no harm in adding it to the template. Cheers!
