### ISSUE TITLE
entrypoint.sh don't execute

### ISSUE THREAD

**Issue by helio-cg** [jackbrycesmith/laravel-caprover-template#4]
the commands that exist in entrypoint.sh are not executed. I always have to access container to run manually

`composer dump-autoload --no-interaction --no-dev --optimize
`

Only then are packages recognized

**Comment by helio-cg** [comment]
this error still remains, the entrypoint.sh does not execute

for exemple: php artisan migrate and composer dump-autoload

**Comment by jackbrycesmith** [comment]
Hi I can't replicate this & unsure why this is happening for you.

If you haven't already, I would recommend trying out https://github.com/jackbrycesmith/laravel-caprover-template/pull/5 & deploying again to a separate test app.

Next time it happens please could you share any related error output after `🎬 entrypoint.sh` in the app logs.

**Comment by helio-cg** [comment]
it's perfect now, the problem was in my application, thanks
