### ISSUE TITLE
Nginx deployment

### ISSUE THREAD

**Issue by faierbol** [jackbrycesmith/laravel-caprover-template#7]
Hi,

I am struggling to deploy my laravel app using this template, it works with caddy but i would like to use nginx. Any help will be much appreciated.

**Comment by jackbrycesmith** [comment]
Hi there,

I use caddy here as I find the syntax easier to understand. If you really want to use nginx, I reccomend you take a look at the following repo for the associated config: https://github.com/TrafeX/docker-php-nginx

Cheers
