### ISSUE TITLE
Passport oauth client, where should I initialize keys?

### ISSUE THREAD

**Issue by darrist** [jackbrycesmith/laravel-caprover-template#8]
Hi, thanks for creating the repo its awesome.

I'd like to know whats ur approach when it comes to passport:install / passport:keys, assuming we want to Laravel to be stateless.

**Comment by jackbrycesmith** [comment]
Hi there 👋,

I would generate the keys on your local machine, then load them as environment variables as mentioned here:  https://laravel.com/docs/7.x/passport#deploying-passport

![image](https://user-images.githubusercontent.com/13235268/92464518-27fd8980-f1c5-11ea-9f3f-f1c02acf25c5.png)

Then make sure to add `PASSPORT_PRIVATE_KEY` & `PASSPORT_PUBLIC_KEY` to the Dockerfile, and you should be good to go!
