### ISSUE TITLE
Scheduler on Multiple Cluster Nodes 

### ISSUE THREAD

**Issue by germanllop** [jackbrycesmith/laravel-caprover-template#9]
I'm having this issue where the schedules are rinning twice, I have two nodes, so it's almost sure it's that.
Any idea how to hack it?

**Comment by jackbrycesmith** [comment]
Laravel spoils us by having [built in support for this scenario!](https://laravel.com/docs/8.x/scheduling#running-tasks-on-one-server) Once you have this setup it should allow you to have multiple nodes, with the command only running once.

![image](https://user-images.githubusercontent.com/13235268/94211239-c7f72a80-fec8-11ea-9292-198c320011c5.png)
